# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'drone-cv' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for drone-cv
  pod 'DJI-SDK-iOS', '~> 4.2'
end
